# valid request
GET http://localhost:4000/ledger
    ?start_date=2011-10-05T14:48:00.000Z
    &end_date=2012-10-05T16:48:00.000Z
    &frequency=FORTNIGHTLY
    &weekly_rent=1200
    &timezone=Europe/London